force-app/main/default/objects/Bowl_Game__c/Bowl_Game__c.object-meta.xml
<CustomObject>
    <label>Bowl Game</label>
    <nameField>
        <label>Bowl Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bowl Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bowl_Game__c/fields/Away_Team__c.field-meta.xml
<CustomField>
    <fullName>Away_Team__c</fullName>
    <label>Away Team</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bowl_Game__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <label>Home Team</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bowl_Game__c/fields/Winner__c.field-meta.xml
<CustomField>
    <fullName>Winner__c</fullName>
    <formula>IF(Home_Points__c &gt; Away_Points__c, Home_Team__c,
			IF(Away_Points__c &gt; Home_Points__c, Away_Team__c,
						IF(Home_Points__c = Away_Points__c, &apos;Tie&apos;,
									NULL)))</formula>
    <label>Winner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bowl_Game__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <referenceTo>Year__c</referenceTo>
    <relationshipLabel>Bowl Games</relationshipLabel>
    <relationshipName>Bowl_Games</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pick__c/Pick__c.object-meta.xml
<CustomObject>
    <label>Pick</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Pick Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pick__c/fields/Assigned_Points__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Points__c</fullName>
    <label>Assigned Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pick__c/fields/Bowl_Game__c.field-meta.xml
<CustomField>
    <fullName>Bowl_Game__c</fullName>
    <label>Bowl Game</label>
    <referenceTo>Bowl_Game__c</referenceTo>
    <relationshipLabel>Picks</relationshipLabel>
    <relationshipName>Picks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pick__c/fields/Bowl_Game_Name__c.field-meta.xml
<CustomField>
    <fullName>Bowl_Game_Name__c</fullName>
    <description>This field is required to store the name of the parent Bowl Game so that it can be referenced in the table component of the pickManager LWC.</description>
    <label>Bowl Game Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pick__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Identify the participant who placed the pick.</description>
    <inlineHelpText>Identify the participant who placed the pick.</inlineHelpText>
    <label>Participant</label>
    <referenceTo>Year_Participated__c</referenceTo>
    <relationshipLabel>Picks</relationshipLabel>
    <relationshipName>Picks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pick__c/fields/Picked_By__c.field-meta.xml
<CustomField>
    <fullName>Picked_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Picked By</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Picks</relationshipLabel>
    <relationshipName>Picks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pick__c/fields/Winner__c.field-meta.xml
<CustomField>
    <fullName>Winner__c</fullName>
    <label>Winner</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pick__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Year</label>
    <referenceTo>Year__c</referenceTo>
    <relationshipLabel>Picks</relationshipLabel>
    <relationshipName>Picks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Year__c/Year__c.object-meta.xml
<CustomObject>
    <label>Year</label>
    <nameField>
        <label>Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Year_Participated__c/Year_Participated__c.object-meta.xml
<CustomObject>
    <description>This will be a junction object that will allow a single Participant to be linked to multiple Years. This object will store data specific to the year they participate.</description>
    <label>Year Participated</label>
    <nameField>
        <displayFormat>YP-{0000}</displayFormat>
        <label>Years Participated Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Years Participated</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Year_Participated__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Years Participated</relationshipLabel>
    <relationshipName>Years_Participated</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Year_Participated__c/fields/Passcode__c.field-meta.xml
<CustomField>
    <fullName>Passcode__c</fullName>
    <description>This is the custom passcode that the user will set each year.</description>
    <label>Passcode</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Year_Participated__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <referenceTo>Year__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Years_Participated</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PickManager.cls
public with sharing class PickManager {

    // public static void createPicks(string participantPasscode) {
    //     Participant__c participant = Database.query('SELECT Id FROM Participant__c WHERE Passcode__c = ' + participantPasscode + 'LIMIT 1');
    //     List<Bowl_Game__c> bowlGames = [SELECT Id, Year__c FROM Bowl_Game__c WHERE Year__c = 'a008b00001ji1bSAAQ'];

    //     for(Bowl_Game__c bg : bowlGames) {
    //         Pick__c pick = new Pick__c(
    //             Bowl_Game__c = bg.Id,
    //             Picked_By__c = participant.Id,
    //             Assigned_Points__c = 0
    //         );
    //     }
    // }

    // public static void editPicks(String participantPasscode) {
    //     List<Pick__c> existingPicks = [SELECT Id, Winner__c, Assigned_Points__c FROM Pick__c WHERE Picked_By__r.Passcode__c = :participantPasscode];
    // }

    @AuraEnabled(cacheable=true)
    public static List<String> getTeams(Id yrId, Id gameId){
        List<String> teams = new List<String>();
        List<Bowl_Game__c> bowlGames = [SELECT Id, Home_Team__c, Away_Team__c FROM Bowl_Game__c WHERE Year__c = :yrId AND Id = :gameId];
        for(Bowl_Game__c bg : bowlGames) {
            teams.add(bg.Home_Team__c);
            teams.add(bg.Away_Team__c);
        }
        return teams;
    }

    @AuraEnabled(cacheable=true)
    public static List<Bowl_Game__c> getBowlGames(Id yrId){
        return [SELECT Id, Name, Home_Team__c, Away_Team__c FROM Bowl_Game__c WHERE Year__c = :yrId];
    }

    @AuraEnabled(cacheable=true)
    public static String getActiveYearId(){
        return [SELECT Id FROM Year__c WHERE Active__c = TRUE LIMIT 1].Id;
    }

    @AuraEnabled
    public static String getBowlGameName(Id bowlGameId){
        return [SELECT Name FROM Bowl_Game__c WHERE Id = :bowlGameId LIMIT 1].Name;
    }

    @AuraEnabled
    public static List<Pick__c> getRelatedPicks(Id yrId){
        return [Select Id, Bowl_Game__c, Bowl_Game_Name__c, Bowl_Game__r.Name, Winner__c, Assigned_Points__c, Year__r.Name from Pick__c where Year__c = :yrId];
    }

    @AuraEnabled
    public static Boolean validatePasscode(String passcode){
        List<Year_Participated__c> yp= [SELECT Id FROM Year_Participated__c WHERE Passcode__c = :passcode LIMIT 1];
        if(!yp.isEmpty()){
            return true;
        }
        else {
            return false;
        }
    }

    @AuraEnabled
    public static String getCurrentParticipantId(String passcode){
        return [SELECT Id FROM Year_Participated__c WHERE Passcode__c = :passcode LIMIT 1].Id;
    }

    @AuraEnabled
    public static List<Pick__c> deletePickHandler(Id pickId, Id yrId){
        Database.delete(pickId);
        return [Select Id, Bowl_Game__c, Bowl_Game_Name__c, Winner__c, Assigned_Points__c, Year__r.Name from Pick__c where Year__c = :yrId];
    }

    @AuraEnabled
    public static List<Pick__c> savePickData(String pickDataString){
        List<Pick__c> pickList = (List<Pick__c>)System.JSON.deserializeStrict(pickDataString, List<Pick__c>.Class);
        Database.insert(pickList);
        return pickList;
    }
}