force-app/main/default/objects/Bowl_Game__c/Bowl_Game__c.object-meta.xml
<CustomObject>
    <label>Bowl Game</label>
    <nameField>
        <label>Bowl Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bowl Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bowl_Game__c/fields/Away_Points__c.field-meta.xml
<CustomField>
    <fullName>Away_Points__c</fullName>
    <label>Away Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bowl_Game__c/fields/Away_Team__c.field-meta.xml
<CustomField>
    <fullName>Away_Team__c</fullName>
    <label>Away Team</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bowl_Game__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this box is checked, it means that the game has been completed. Populated from a callout to the external college football API.</description>
    <inlineHelpText>If this box is checked, it means that the game has been completed. Populated from a callout to the external college football API.</inlineHelpText>
    <label>Completed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bowl_Game__c/fields/Game_ID__c.field-meta.xml
<CustomField>
    <fullName>Game_ID__c</fullName>
    <description>This is the ID pulled from the API. Used to identify the specific bowl game.</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the ID pulled from the API. Used to identify the specific bowl game.</inlineHelpText>
    <label>Game ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bowl_Game__c/fields/Home_Points__c.field-meta.xml
<CustomField>
    <fullName>Home_Points__c</fullName>
    <label>Home Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bowl_Game__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <label>Home Team</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bowl_Game__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date the Bowl Game will be played on. Pulled in from the external college football API.</description>
    <inlineHelpText>Date the Bowl Game will be played on. Pulled in from the external college football API.</inlineHelpText>
    <label>Start Date</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bowl_Game__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <referenceTo>Year__c</referenceTo>
    <relationshipLabel>Bowl Games</relationshipLabel>
    <relationshipName>Bowl_Games</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Year__c/Year__c.object-meta.xml
<CustomObject>
    <label>Year</label>
    <nameField>
        <label>Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Year__c/fields/Bowl_Games_Imported__c.field-meta.xml
<CustomField>
    <fullName>Bowl_Games_Imported__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will get checked once the Bowl Games for a particular year have been imported. If checked, the &apos;Import Bowl Games&apos; button will be rendered disabled.</description>
    <inlineHelpText>This field will get checked once the Bowl Games for a particular year have been imported. If checked, the &apos;Import Bowl Games&apos; button will be rendered disabled.</inlineHelpText>
    <label>Bowl Games Imported</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CollegeFootballCallout.cls
/*This class will make the callout to the college football API and return the bowl game data for a specified year.
*/
public class CollegeFootballCallout {

    @AuraEnabled
    public static void importBowlGames(Id yearId) {
        
        Year__c year = [SELECT Id, Name FROM Year__c WHERE Id = :yearId LIMIT 1];
        List<Bowl_Game__c> bowlGamesToCreate = new List<Bowl_Game__c>();
        List<CollegeFootballWrapper> wrapper = makeCallout(yearId);

        for(CollegeFootballWrapper bowlGame : wrapper){
            Bowl_Game__c bg = new Bowl_Game__c();
            bg.Name = bowlGame.notes.left(80); //the name field can only be 80 characters long
            bg.Year__c = yearId;
            bg.Game_ID__c = String.valueOf(bowlGame.id);
            bg.Home_Team__c = bowlGame.home_team;
            bg.Home_Points__c = bowlGame.home_points;
            bg.Away_Team__c = bowlGame.away_team;
            bg.Away_Points__c = bowlGame.away_points;
            bg.Start_Date__c = bowlGame.start_date;
            bg.Completed__c = bowlGame.completed;
            bowlGamesToCreate.add(bg);
        }
        System.debug('Number Of Bowl Games: ' + wrapper.size());
        try {
            insert bowlGamesToCreate;
            year.Bowl_Games_Imported__c = true;
            update year;
        } catch (Exception e) {
            System.debug('An error occurred when attempting to retrieve bowl games: ' + e.getMessage());
        }
    }

    @AuraEnabled
    public static void updateBowlGames(Id yearId){

        List<Bowl_Game__c> bowlGamesToUpdate = new List<Bowl_Game__c>();
        List<Bowl_Game__c> existingBowlGames = [SELECT Id, Name, Year__c, Game_ID__c, Home_Team__c, Home_Points__c, Away_Team__c, Away_Points__c, Start_Date__c, Completed__c FROM Bowl_Game__c WHERE Year__c = :yearId];
        Map<String, Bowl_Game__c> existingBowlGamesMap = new Map<String, Bowl_Game__c>();
        for(Bowl_Game__c bg : existingBowlGames) {
            existingBowlGamesMap.put(bg.Game_ID__c, bg);
        }

        List<CollegeFootballWrapper> wrapper = makeCallout(yearId);

        for(CollegeFootballWrapper bowlGame : wrapper){
            Bowl_Game__c bg = new Bowl_Game__c();
            bg.Id = existingBowlGamesMap.get(String.valueOf(bowlGame.id)).Id;
            bg.Home_Points__c = bowlGame.home_points;
            bg.Away_Points__c = bowlGame.away_points;
            bg.Completed__c = bowlGame.completed;
            bowlGamesToUpdate.add(bg);
        }
        try {
            update bowlGamesToUpdate;
        } catch (Exception e) {
            System.debug('An error occurred when attempting to update bowl games: ' + e.getMessage());
        }
    }

    public static List<CollegeFootballWrapper> makeCallout(Id yearId) {

        Year__c year = [SELECT Id, Name FROM Year__c WHERE Id = :yearId LIMIT 1];
        HttpRequest req = new HttpRequest();
        req.setHeader('Accept', 'application/json');
        req.setHeader('Content-Type', 'application/json');
        req.setMethod('GET');
        Http http = new Http();

        String baseEndpoint = 'callout:CollegeFootballAPI' + '/games?seasonType=postseason&year=' + year.Name + '&division=fbs';
        req.setEndpoint(baseEndpoint);
        HttpResponse res = http.send(req);

        //returns in the format of List<CollegeFootballWrapper>
        return CollegeFootballWrapper.parse(res.getBody());
    }
}