force-app/main/default/objects/Bowl_Game__c/Bowl_Game__c.object-meta.xml
<CustomObject>
    <label>Bowl Game</label>
    <nameField>
        <label>Bowl Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bowl Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bowl_Game__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this box is checked, it means that the game has been completed. Populated from a callout to the external college football API.</description>
    <inlineHelpText>If this box is checked, it means that the game has been completed. Populated from a callout to the external college football API.</inlineHelpText>
    <label>Completed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bowl_Game__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <referenceTo>Year__c</referenceTo>
    <relationshipLabel>Bowl Games</relationshipLabel>
    <relationshipName>Bowl_Games</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pick__c/Pick__c.object-meta.xml
<CustomObject>
    <label>Pick</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Pick Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pick__c/fields/Assigned_Points__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Points__c</fullName>
    <label>Assigned Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pick__c/fields/Bowl_Game__c.field-meta.xml
<CustomField>
    <fullName>Bowl_Game__c</fullName>
    <label>Bowl Game</label>
    <referenceTo>Bowl_Game__c</referenceTo>
    <relationshipLabel>Picks</relationshipLabel>
    <relationshipName>Picks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pick__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Identify the participant who placed the pick.</description>
    <inlineHelpText>Identify the participant who placed the pick.</inlineHelpText>
    <label>Participant</label>
    <referenceTo>Year_Participated__c</referenceTo>
    <relationshipLabel>Picks</relationshipLabel>
    <relationshipName>Picks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pick__c/fields/Picked_Correctly__c.field-meta.xml
<CustomField>
    <fullName>Picked_Correctly__c</fullName>
    <formula>IF(Winner__c = Bowl_Game__r.Winner__c, true, false)</formula>
    <label>Picked Correctly?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Pick__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Year</label>
    <referenceTo>Year__c</referenceTo>
    <relationshipLabel>Picks</relationshipLabel>
    <relationshipName>Picks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Year__c/Year__c.object-meta.xml
<CustomObject>
    <label>Year</label>
    <nameField>
        <label>Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Year__c/fields/First_Place__c.field-meta.xml
<CustomField>
    <fullName>First_Place__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First Place</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Years They Won</relationshipLabel>
    <relationshipName>Years_They_Won</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Year__c/fields/Last_Place_DFL__c.field-meta.xml
<CustomField>
    <fullName>Last_Place_DFL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Place (DFL)</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Years They Got Last Place (DFL)</relationshipLabel>
    <relationshipName>Years_They_Got_Last_Place_DFL</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Year__c/fields/Second_Place__c.field-meta.xml
<CustomField>
    <fullName>Second_Place__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Second Place</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Years They Got Second Place</relationshipLabel>
    <relationshipName>Years_They_Got_Second_Place</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Year_Participated__c/Year_Participated__c.object-meta.xml
<CustomObject>
    <description>This will be a junction object that will allow a single Participant to be linked to multiple Years. This object will store data specific to the year they participate.</description>
    <label>Year Participated</label>
    <nameField>
        <displayFormat>YP-{0000}</displayFormat>
        <label>Years Participated Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Years Participated</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Year_Participated__c/fields/Earned_Points__c.field-meta.xml
<CustomField>
    <fullName>Earned_Points__c</fullName>
    <description>This will be the sum of the &apos;Assigned Points&apos; fields for all of the participants&apos; correct picks. Automatically calculated by an Apex job.</description>
    <inlineHelpText>This will be the sum of the &apos;Assigned Points&apos; fields for all of the participants&apos; correct picks. Automatically calculated by an Apex job.</inlineHelpText>
    <label>Earned Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Year_Participated__c/fields/Number_of_Correct_Picks__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Correct_Picks__c</fullName>
    <description>This will be the number of correctly placed picks. It will be calculated by an automated Apex job.</description>
    <inlineHelpText>This will be the number of correctly placed picks. It will be calculated by an automated Apex job.</inlineHelpText>
    <label>Number of Correct Picks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Year_Participated__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Years Participated</relationshipLabel>
    <relationshipName>Years_Participated</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Year_Participated__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <referenceTo>Year__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Years_Participated</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BowlGameUtil.cls
public with sharing class BowlGameUtil {

    public static void sumEarnedPoints(List<Bowl_Game__c> newBowlGames, Map<Id,Bowl_Game__c> oldBowlGamesMap) {
        Boolean executeSumCalculation = false;
        for(Bowl_Game__c bg : newBowlGames) {
            if(bg.Completed__c == true && oldBowlGamesMap.get(bg.Id).Completed__c == false){
                executeSumCalculation = true;
                break;
            }
        }
        if(executeSumCalculation){
            List<Year_Participated__c> yearsParticipatedToUpdate = new List<Year_Participated__c>();
            List<AggregateResult> correctPicks = [SELECT Participant__c, Count(Id) numberOfCorrectPicks, SUM(Assigned_Points__c) earnedPoints FROM Pick__c WHERE Bowl_Game__r.Completed__c = true  AND Picked_Correctly__c = true GROUP BY Participant__c];
            for(AggregateResult aggr : correctPicks) {
                Year_Participated__c yp = new Year_Participated__c();
                yp.Id = (Id)aggr.get('Participant__c');
                yp.Earned_Points__c = (Double)aggr.get('earnedPoints');
                yp.Number_of_Correct_Picks__c = (Double)aggr.get('numberOfCorrectPicks');
                yearsParticipatedToUpdate.add(yp);
                System.debug('ParticipantId: ' + yp.Id);
                System.debug('participant earned points: ' + yp.Earned_Points__c);
                System.debug('participant correct picks: ' + yp.Number_of_Correct_Picks__c);
            }
            if(!yearsParticipatedToUpdate.isEmpty()){
                try{
                    update yearsParticipatedToUpdate;
                    setKeyParticipants(yearsParticipatedToUpdate);
                }
                catch(Exception e){
                    System.debug('Exception occured while updating the earned points values: ' + e.getMessage());
                }
            }
        }
    }

    public static void setKeyParticipants(List<Year_Participated__c> yearsParticipated) {
        Year__c activeYear = [SELECT Id, First_Place__c, Second_Place__c, Last_Place_DFL__c FROM Year__c WHERE Active__c = true LIMIT 1];
        List<Year_Participated__c> ypList = [SELECT Id, Participant__c FROM Year_Participated__c WHERE Id IN :yearsParticipated ORDER BY Earned_Points__c DESC];
        activeYear.First_Place__c = ypList[0].Participant__c;
        activeYear.Second_Place__c = ypList[1].Participant__c;
        activeYear.Last_Place_DFL__c = ypList[ypList.size()-1].Participant__c;
        try{
            update activeYear;
        }
        catch(Exception e){
            System.debug('Exception occured while updating the key participants for the active year: ' + e.getMessage());
        }
    }
}